---
title: "main-functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{main-functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(measlesanalyze)
```

```{r}
load_data_month()
load_data_year()
load_data_covid()
load_data_gdp()

# These lines of code should read in their respective data sets. There should be four sets: montly measles data, yearly measles data, Covid-19 data, and GDP growth data.
```

```{r}
calc_concentration(year_in = 2013)

# This should wrangle the yearly measles data set in order to reflect the concentration of measles cases in each country during the specified year. In this case, the data set should end up reflecting the concentration of all countries in the year 2013.
```

```{r}
summarize_concentration(yr = 2013)

# This should further wrangle the yearly measles data set output from calc_concentration() to emphasize more specific countries. In this case, the data set should up end reflecting the concentration of all countries in the year 2013 while identifying the top country that has the most impact.
```

```{r}
measles_concentration(start_year = 2013, end_year = 2023)

# This should make a table showing the concentration of measles cases by year across countries. It also highlights what share of global measles cases and country is responsible for. In this cases, we are looking at global measles cases ranging between 2013 and 2023.
```

```{r}
plot_measles_heatmap(start_year = 2013, end_year = 2023)

# This should make a heatmap showing the top 15 countries with the highest concentration of measles cases over the selected study period (from the start year to the end year), which in this case is from 2013 to 2023.
```

```{r}
measles_covid_compare(year1 = 2020)

# This should join and wrangle the yearly mealses and Covid-19 data sets in order to match years/countries and see the comparison. In this case, the data set should end up reflecting the comparison of measles and Covid-19 cases in the year 2020.
```

```{r}
measles_vs_covid(year1 = 2020, year2 = 2022)

# This should make a table comparing measles and Covid-19 cases from the top 10 countries with the highest number of Covid-19 cases in the two selected years, which in this case is 2020 and 2022.
```

```{r}
measles_covid_barplot(year = 2020)

# This should make a horizontal bar plot showing the difference in measles and Covid-19 cases in the top 10 countries during a specified year. In this case, the plot will show the comparison of the two diseases in 2020.
```

```{r}
gdp_ttest(year_in = 2019)

# This should make a table showing the results of a two sample t-test; it compares the mean GDP growth of countries between high and low measles concentrations in a specified year. In this case, the table will show the results when analyzing the year 2019.
```


